blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/yansircc/payload-builder/wiki
    about: Check our documentation first
  - name: ğŸ’¬ Discussions
    url: https://github.com/yansircc/payload-builder/discussions
    about: Please ask and answer questions here
